-- Seed the ISO 4217 currency list as fiat assets: one `assets` spine row plus
-- one `fiat_assets` detail row per currency, matched on the alphabetic code.
WITH iso_4217 (code, numeric_code, asset_name, symbol, minor_units) AS (
    VALUES
    ('AED', '784', 'UAE Dirham', NULL, 2),
    ('AFN', '971', 'Afghani', NULL, 2),
    ('ALL', '008', 'Lek', NULL, 2),
    ('AMD', '051', 'Armenian Dram', NULL, 2),
    ('AOA', '973', 'Kwanza', NULL, 2),
    ('ARS', '032', 'Argentine Peso', NULL, 2),
    ('AUD', '036', 'Australian Dollar', '$', 2),
    ('AWG', '533', 'Aruban Florin', NULL, 2),
    ('AZN', '944', 'Azerbaijan Manat', NULL, 2),
    ('BAM', '977', 'Convertible Mark', NULL, 2),
    ('BBD', '052', 'Barbados Dollar', '$', 2),
    ('BDT', '050', 'Taka', NULL, 2),
    ('BHD', '048', 'Bahraini Dinar', NULL, 3),
    ('BIF', '108', 'Burundi Franc', NULL, 0),
    ('BMD', '060', 'Bermudian Dollar', '$', 2),
    ('BND', '096', 'Brunei Dollar', '$', 2),
    ('BOB', '068', 'Boliviano', NULL, 2),
    ('BOV', '984', 'Mvdol', NULL, 2),
    ('BRL', '986', 'Brazilian Real', 'R$', 2),
    ('BSD', '044', 'Bahamian Dollar', '$', 2),
    ('BTN', '064', 'Ngultrum', NULL, 2),
    ('BWP', '072', 'Pula', NULL, 2),
    ('BYN', '933', 'Belarusian Ruble', NULL, 2),
    ('BZD', '084', 'Belize Dollar', '$', 2),
    ('CAD', '124', 'Canadian Dollar', '$', 2),
    ('CDF', '976', 'Congolese Franc', NULL, 2),
    ('CHE', '947', 'WIR Euro', NULL, 2),
    ('CHF', '756', 'Swiss Franc', NULL, 2),
    ('CHW', '948', 'WIR Franc', NULL, 2),
    ('CLF', '990', 'Unidad de Fomento', NULL, 4),
    ('CLP', '152', 'Chilean Peso', NULL, 0),
    ('CNY', '156', 'Yuan Renminbi', '¥', 2),
    ('COP', '170', 'Colombian Peso', NULL, 2),
    ('COU', '970', 'Unidad de Valor Real', NULL, 2),
    ('CRC', '188', 'Costa Rican Colon', '₡', 2),
    ('CUP', '192', 'Cuban Peso', NULL, 2),
    ('CVE', '132', 'Cabo Verde Escudo', NULL, 2),
    ('CZK', '203', 'Czech Koruna', 'Kč', 2),
    ('DJF', '262', 'Djibouti Franc', NULL, 0),
    ('DKK', '208', 'Danish Krone', 'kr', 2),
    ('DOP', '214', 'Dominican Peso', NULL, 2),
    ('DZD', '012', 'Algerian Dinar', NULL, 2),
    ('EGP', '818', 'Egyptian Pound', NULL, 2),
    ('ERN', '232', 'Nakfa', NULL, 2),
    ('ETB', '230', 'Ethiopian Birr', NULL, 2),
    ('EUR', '978', 'Euro', '€', 2),
    ('FJD', '242', 'Fiji Dollar', '$', 2),
    ('FKP', '238', 'Falkland Islands Pound', '£', 2),
    ('GBP', '826', 'Pound Sterling', '£', 2),
    ('GEL', '981', 'Lari', NULL, 2),
    ('GHS', '936', 'Ghana Cedi', NULL, 2),
    ('GIP', '292', 'Gibraltar Pound', '£', 2),
    ('GMD', '270', 'Dalasi', NULL, 2),
    ('GNF', '324', 'Guinean Franc', NULL, 0),
    ('GTQ', '320', 'Quetzal', NULL, 2),
    ('GYD', '328', 'Guyana Dollar', '$', 2),
    ('HKD', '344', 'Hong Kong Dollar', '$', 2),
    ('HNL', '340', 'Lempira', NULL, 2),
    ('HTG', '332', 'Gourde', NULL, 2),
    ('HUF', '348', 'Forint', NULL, 2),
    ('IDR', '360', 'Rupiah', NULL, 2),
    ('ILS', '376', 'New Israeli Sheqel', '₪', 2),
    ('INR', '356', 'Indian Rupee', '₹', 2),
    ('IQD', '368', 'Iraqi Dinar', NULL, 3),
    ('IRR', '364', 'Iranian Rial', NULL, 2),
    ('ISK', '352', 'Iceland Krona', 'kr', 0),
    ('JMD', '388', 'Jamaican Dollar', '$', 2),
    ('JOD', '400', 'Jordanian Dinar', NULL, 3),
    ('JPY', '392', 'Yen', '¥', 0),
    ('KES', '404', 'Kenyan Shilling', NULL, 2),
    ('KGS', '417', 'Som', NULL, 2),
    ('KHR', '116', 'Riel', NULL, 2),
    ('KMF', '174', 'Comorian Franc', NULL, 0),
    ('KPW', '408', 'North Korean Won', '₩', 2),
    ('KRW', '410', 'Won', '₩', 0),
    ('KWD', '414', 'Kuwaiti Dinar', NULL, 3),
    ('KYD', '136', 'Cayman Islands Dollar', '$', 2),
    ('KZT', '398', 'Tenge', NULL, 2),
    ('LAK', '418', 'Lao Kip', NULL, 2),
    ('LBP', '422', 'Lebanese Pound', NULL, 2),
    ('LKR', '144', 'Sri Lanka Rupee', NULL, 2),
    ('LRD', '430', 'Liberian Dollar', '$', 2),
    ('LSL', '426', 'Loti', NULL, 2),
    ('LYD', '434', 'Libyan Dinar', NULL, 3),
    ('MAD', '504', 'Moroccan Dirham', NULL, 2),
    ('MDL', '498', 'Moldovan Leu', NULL, 2),
    ('MGA', '969', 'Malagasy Ariary', NULL, 2),
    ('MKD', '807', 'Denar', NULL, 2),
    ('MMK', '104', 'Kyat', NULL, 2),
    ('MNT', '496', 'Tugrik', NULL, 2),
    ('MOP', '446', 'Pataca', NULL, 2),
    ('MRU', '929', 'Ouguiya', NULL, 2),
    ('MUR', '480', 'Mauritius Rupee', NULL, 2),
    ('MVR', '462', 'Rufiyaa', NULL, 2),
    ('MWK', '454', 'Malawi Kwacha', NULL, 2),
    ('MXN', '484', 'Mexican Peso', '$', 2),
    ('MXV', '979', 'Mexican Unidad de Inversion (UDI)', NULL, 2),
    ('MYR', '458', 'Malaysian Ringgit', NULL, 2),
    ('MZN', '943', 'Mozambique Metical', NULL, 2),
    ('NAD', '516', 'Namibia Dollar', '$', 2),
    ('NGN', '566', 'Naira', '₦', 2),
    ('NIO', '558', 'Cordoba Oro', NULL, 2),
    ('NOK', '578', 'Norwegian Krone', 'kr', 2),
    ('NPR', '524', 'Nepalese Rupee', NULL, 2),
    ('NZD', '554', 'New Zealand Dollar', '$', 2),
    ('OMR', '512', 'Rial Omani', NULL, 3),
    ('PAB', '590', 'Balboa', NULL, 2),
    ('PEN', '604', 'Sol', NULL, 2),
    ('PGK', '598', 'Kina', NULL, 2),
    ('PHP', '608', 'Philippine Peso', '₱', 2),
    ('PKR', '586', 'Pakistan Rupee', NULL, 2),
    ('PLN', '985', 'Zloty', 'zł', 2),
    ('PYG', '600', 'Guarani', NULL, 0),
    ('QAR', '634', 'Qatari Rial', NULL, 2),
    ('RON', '946', 'Romanian Leu', NULL, 2),
    ('RSD', '941', 'Serbian Dinar', NULL, 2),
    ('RUB', '643', 'Russian Ruble', '₽', 2),
    ('RWF', '646', 'Rwanda Franc', NULL, 0),
    ('SAR', '682', 'Saudi Riyal', NULL, 2),
    ('SBD', '090', 'Solomon Islands Dollar', '$', 2),
    ('SCR', '690', 'Seychelles Rupee', NULL, 2),
    ('SDG', '938', 'Sudanese Pound', NULL, 2),
    ('SEK', '752', 'Swedish Krona', 'kr', 2),
    ('SGD', '702', 'Singapore Dollar', '$', 2),
    ('SHP', '654', 'Saint Helena Pound', '£', 2),
    ('SLE', '925', 'Leone', NULL, 2),
    ('SOS', '706', 'Somali Shilling', NULL, 2),
    ('SRD', '968', 'Surinam Dollar', '$', 2),
    ('SSP', '728', 'South Sudanese Pound', NULL, 2),
    ('STN', '930', 'Dobra', NULL, 2),
    ('SVC', '222', 'El Salvador Colon', NULL, 2),
    ('SYP', '760', 'Syrian Pound', NULL, 2),
    ('SZL', '748', 'Lilangeni', NULL, 2),
    ('THB', '764', 'Baht', '฿', 2),
    ('TJS', '972', 'Somoni', NULL, 2),
    ('TMT', '934', 'Turkmenistan New Manat', NULL, 2),
    ('TND', '788', 'Tunisian Dinar', NULL, 3),
    ('TOP', '776', 'Pa’anga', NULL, 2),
    ('TRY', '949', 'Turkish Lira', '₺', 2),
    ('TTD', '780', 'Trinidad and Tobago Dollar', '$', 2),
    ('TWD', '901', 'New Taiwan Dollar', '$', 2),
    ('TZS', '834', 'Tanzanian Shilling', NULL, 2),
    ('UAH', '980', 'Hryvnia', '₴', 2),
    ('UGX', '800', 'Uganda Shilling', NULL, 0),
    ('USD', '840', 'US Dollar', '$', 2),
    ('USN', '997', 'US Dollar (Next day)', NULL, 2),
    ('UYI', '940', 'Uruguay Peso en Unidades Indexadas (UI)', NULL, 0),
    ('UYU', '858', 'Peso Uruguayo', NULL, 2),
    ('UYW', '927', 'Unidad Previsional', NULL, 4),
    ('UZS', '860', 'Uzbekistan Sum', NULL, 2),
    ('VED', '926', 'Bolívar Soberano', NULL, 2),
    ('VES', '928', 'Bolívar Soberano', NULL, 2),
    ('VND', '704', 'Dong', '₫', 0),
    ('VUV', '548', 'Vatu', NULL, 0),
    ('WST', '882', 'Tala', NULL, 2),
    ('XAD', '396', 'Arab Accounting Dinar', NULL, 2),
    ('XAF', '950', 'CFA Franc BEAC', NULL, 0),
    ('XCD', '951', 'East Caribbean Dollar', '$', 2),
    ('XCG', '532', 'Caribbean Guilder', NULL, 2),
    ('XOF', '952', 'CFA Franc BCEAO', NULL, 0),
    ('XPF', '953', 'CFP Franc', NULL, 0),
    ('YER', '886', 'Yemeni Rial', NULL, 2),
    ('ZAR', '710', 'Rand', 'R', 2),
    ('ZMW', '967', 'Zambian Kwacha', NULL, 2),
    ('ZWG', '924', 'Zimbabwe Gold', NULL, 2)
),

inserted_assets AS (
    INSERT INTO assets (asset_class, code, asset_name, symbol)
    SELECT
        'fiat' AS asset_class,
        code,
        asset_name,
        symbol
    FROM iso_4217
    RETURNING id, code
)

INSERT INTO fiat_assets (asset_id, numeric_code, minor_units)
SELECT
    inserted_assets.id,
    iso_4217.numeric_code,
    iso_4217.minor_units
FROM inserted_assets
INNER JOIN iso_4217 ON inserted_assets.code = iso_4217.code;
